--------------------------------------------------------
--  File created - Thursday-January-04-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence GRPSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHAT"."GRPSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN_DATA
--------------------------------------------------------

  CREATE TABLE "CHAT"."ADMIN_DATA" 
   (	"ADMIN_USER_NAME" VARCHAR2(50 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(50 BYTE), 
	"ADMIN_GENDER" VARCHAR2(20 BYTE), 
	"ADMIN_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT_DATA
--------------------------------------------------------

  CREATE TABLE "CHAT"."CLIENT_DATA" 
   (	"CLIENT_PIC" BLOB, 
	"CLIENT_USER_NAME" VARCHAR2(50 BYTE), 
	"CLIENT_NAME" VARCHAR2(50 BYTE), 
	"GR_ID" VARCHAR2(50 BYTE), 
	"CLIENT_PASSWORD" VARCHAR2(50 BYTE), 
	"CLIENT_GENDER" VARCHAR2(20 BYTE), 
	"CLIENT_STATUS" VARCHAR2(20 BYTE), 
	"CLIENT_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CLIENT_PIC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONTACT_LIST
--------------------------------------------------------

  CREATE TABLE "CHAT"."CONTACT_LIST" 
   (	"CONTACT_USER_NAME" VARCHAR2(50 BYTE), 
	"CLIENT_USER_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP_DATA
--------------------------------------------------------

  CREATE TABLE "CHAT"."GROUP_DATA" 
   (	"GR_ID" VARCHAR2(50 BYTE), 
	"GROUP_USER_NAME" VARCHAR2(50 BYTE), 
	"GROUP_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "CHAT"."MESSAGES" 
   (	"SENDER_USER_NAME" VARCHAR2(50 BYTE), 
	"RECEIVER_USER_NAME" VARCHAR2(50 BYTE), 
	"MESSAGE" VARCHAR2(1000 BYTE), 
	"MSG_COLOR" VARCHAR2(50 BYTE), 
	"MSG_FONT" VARCHAR2(100 BYTE), 
	"MSG_SIZE" VARCHAR2(20 BYTE), 
	"MSG_DATE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUESTS
--------------------------------------------------------

  CREATE TABLE "CHAT"."REQUESTS" 
   (	"SENDER_USER_NAME" VARCHAR2(50 BYTE), 
	"RECEIVER_USER_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CHAT.ADMIN_DATA
SET DEFINE OFF;
Insert into CHAT.ADMIN_DATA (ADMIN_USER_NAME,ADMIN_PASSWORD,ADMIN_GENDER,ADMIN_ADDRESS) values ('ahmedosman','ahmed123456','male','aa');
REM INSERTING into CHAT.CLIENT_DATA
SET DEFINE OFF;
Insert into CHAT.CLIENT_DATA (CLIENT_USER_NAME,CLIENT_NAME,GR_ID,CLIENT_PASSWORD,CLIENT_GENDER,CLIENT_STATUS,CLIENT_ADDRESS) values ('ahmedosman','Ahmed Osman',null,'ahmed123456','male','Online','Helioplis');
Insert into CHAT.CLIENT_DATA (CLIENT_USER_NAME,CLIENT_NAME,GR_ID,CLIENT_PASSWORD,CLIENT_GENDER,CLIENT_STATUS,CLIENT_ADDRESS) values ('yasminahmed','Yasmin Ahmed',null,'yasmin123456','female','Online','isamillia');
Insert into CHAT.CLIENT_DATA (CLIENT_USER_NAME,CLIENT_NAME,GR_ID,CLIENT_PASSWORD,CLIENT_GENDER,CLIENT_STATUS,CLIENT_ADDRESS) values ('emanelsayed','Eman El-Sayed',null,'eman123456','female','online','mansoura');
Insert into CHAT.CLIENT_DATA (CLIENT_USER_NAME,CLIENT_NAME,GR_ID,CLIENT_PASSWORD,CLIENT_GENDER,CLIENT_STATUS,CLIENT_ADDRESS) values ('raniaramadan','Rania Ramadan',null,'rania123456','female','online','sharquia');
Insert into CHAT.CLIENT_DATA (CLIENT_USER_NAME,CLIENT_NAME,GR_ID,CLIENT_PASSWORD,CLIENT_GENDER,CLIENT_STATUS,CLIENT_ADDRESS) values ('emanahmed','Eman Ahmed',null,'eman123456','female','online','cairo');
REM INSERTING into CHAT.CONTACT_LIST
SET DEFINE OFF;
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('ahmedosman','yasminahmed');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('yasminahmed','ahmedosman');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('ahmedosman','emanahmed');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('ahmedosman','emanelsayed');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('ahmedosman','raniaramadan');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('raniaramadan','ahmedosman');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('emanahmed','ahmedosman');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('emanelsayed','ahmedosman');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('emanelsayed','yasminahmed');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('yasminahmed','emanelsayed');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('yasminahmed','raniaramadan');
Insert into CHAT.CONTACT_LIST (CONTACT_USER_NAME,CLIENT_USER_NAME) values ('raniaramadan','yasminahmed');
REM INSERTING into CHAT.GROUP_DATA
SET DEFINE OFF;
REM INSERTING into CHAT.MESSAGES
SET DEFINE OFF;
REM INSERTING into CHAT.REQUESTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_USER_NAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHAT"."CLIENT_USER_NAME_PK" ON "CHAT"."CLIENT_DATA" ("CLIENT_USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_USER_NAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHAT"."ADMIN_USER_NAME_PK" ON "CHAT"."ADMIN_DATA" ("ADMIN_USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_DATA
--------------------------------------------------------

  ALTER TABLE "CHAT"."ADMIN_DATA" ADD CONSTRAINT "ADMIN_USER_NAME_PK" PRIMARY KEY ("ADMIN_USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CHAT"."ADMIN_DATA" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CHAT"."ADMIN_DATA" MODIFY ("ADMIN_USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTACT_LIST
--------------------------------------------------------

  ALTER TABLE "CHAT"."CONTACT_LIST" MODIFY ("CONTACT_USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT_DATA
--------------------------------------------------------

  ALTER TABLE "CHAT"."CLIENT_DATA" ADD CONSTRAINT "CLIENT_USER_NAME_PK" PRIMARY KEY ("CLIENT_USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CHAT"."CLIENT_DATA" MODIFY ("CLIENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHAT"."CLIENT_DATA" MODIFY ("CLIENT_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CHAT"."CLIENT_DATA" MODIFY ("CLIENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTACT_LIST
--------------------------------------------------------

  ALTER TABLE "CHAT"."CONTACT_LIST" ADD CONSTRAINT "CLIENT_USER_NAME_FK" FOREIGN KEY ("CLIENT_USER_NAME")
	  REFERENCES "CHAT"."CLIENT_DATA" ("CLIENT_USER_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "CHAT"."MESSAGES" ADD CONSTRAINT "SENDER_USER_NAME_FK" FOREIGN KEY ("SENDER_USER_NAME")
	  REFERENCES "CHAT"."CLIENT_DATA" ("CLIENT_USER_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUESTS
--------------------------------------------------------

  ALTER TABLE "CHAT"."REQUESTS" ADD CONSTRAINT "SENDER_USER_FK" FOREIGN KEY ("SENDER_USER_NAME")
	  REFERENCES "CHAT"."CLIENT_DATA" ("CLIENT_USER_NAME") ENABLE;
